name: Push To Yandex Cloud CR

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_CREDS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ vars.CR_REGISTRY }}
          CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest --target prod .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1
        env:
          CR_REGISTRY: $ {{ vars.CR_REGISTRY }}
          CR_REPOSITORY: $ {{ vars.CR_REPOSITORY }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_CREDS }}
          folder-id: ${{ vars.FOLDER_ID }}
          VM-name: ds2tg-bot
          vm-service-account-id: $ {{ vars.SERVICE_ACCOUNT_ID }}
          vm-cores: 1
          vm-memory: 512Mb
          vm-core-fraction: 20
          vm-subnet-id: default
