name: Push To Yandex Cloud CR

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_CREDS }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ vars.CR_REGISTRY }}
          CR_REPOSITORY: ${{ vars.CR_REPOSITORY }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest --target prod .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:latest
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1
        env:
          CR_REGISTRY: $ {{ vars.CR_REGISTRY }}
          CR_REPOSITORY: $ {{ vars.CR_REPOSITORY }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDS }}
          folder-id: ${{ vars.FOLDER_ID }}
          VM-name: ds2tg-bot
          vm-service-account-id: $ {{ vars.SERVICE_ACCOUNT_ID }}
          vm-cores: 1
          vm-memory: 512Mb
          vm-core-fraction: 20
          vm-subnet-id: default



'''
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_CREDS }}
          container-name: ${{ vars.CONTAINER_NAME }}
          folder-id: ${{ vars.FOLDER_ID }}
          revision-service-account-id: ${{ vars.SERVICE_ACCOUNT_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 1
          revision-image-url: cr.yandex/${{ vars.CR_REGISTRY }}/${{ vars.CR_REPOSITORY }}:latest
          revision-execution-timeout: 10
          revision-env: |
            DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
            DISCORD_CHANNELS=${{ vars.DISCORD_CHANNELS }}
            TELEGRAM_CHANNELS=${{ vars.TELEGRAM_CHANNELS }}
'''