name: Curl Request

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_call:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: IAM Token
      id: iam-token
      with:
        yc-sa-json-credentials: ${{ secrets.YC_CREDS }}
      uses: yc-actions/yc-iam-token@v1
    - name: Trigger Container
      id: trigger
      run: |
        bash -c 'id=$(curl -H "Authorization: Bearer ${{ steps.iam-token.outputs.token }}" https://serverless-containers.api.cloud.yandex.net/containers/v1/containers\?folder_id\=${{ vars.FOLDER_ID }} | jq ".containers[] | select(.name == \"${{ vars.CONTAINER_NAME }}\").id"); curl -H "Authorization: Bearer ${{ steps.iam-token.outputs.token }}" -m 20 https://$(id).containers.yandexcloud.net || :'
